version: '3.7'

networks:
  tqs_project_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/16"

services:

  db:
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: TQS
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    healthcheck:
      test: "mysql TQS -uroot -puser -e 'SELECT 1;'"
      interval: 30s
      timeout: 20s
      retries: 2
    networks:
      tqs_project_network:
        ipv4_address: "172.24.0.2"

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
                      "spring.datasource.url" : "jdbc:mysql://db:3306/TQS?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC",
                      "spring.datasource.username" : "user",
                      "spring.datasource.password" : "user",
                      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
                      "spring.jpa.hibernate.ddl-auto" : "update"
                      }'
    ports:
      - "8080:8080"
    networks:
      tqs_project_network:
        ipv4_address: "172.24.0.3"

  staff:
    build: ./staff_portal
    depends_on:
      - backend
    ports:
      - "3001:3001"
    networks:
      tqs_project_network:
        ipv4_address: "172.24.0.4"

  board:
    build: ./board
    depends_on:
      - backend
    ports:
      - "3002:3002"
    networks:
      tqs_project_network:
        ipv4_address: "172.24.0.5"

  costumer:
    build: ./customer_portal
    depends_on:
      - backend
    ports:
      - "3003:3003"
    networks:
      tqs_project_network:
        ipv4_address: "172.24.0.6"
