name: functional tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build and test frontend
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Install Chrome
        run: |
          sudo snap remove google-chrome
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get update
          sudo apt install -y ./google-chrome-stable_current_amd64.deb --allow-downgrades

      - name: mvn package
        run: cd backend && mvn package

      - name: Up containers
        run: docker compose up -d --build

      - name: Run functional tests
        run: mvn test -Dtest=*TestRunner
        working-directory: backend

      - name: Tear down the stack
        run: |
          docker compose down --volumes
          docker builder prune -a -f
