name: functional tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update
          sudo apt install google-chrome-stable -y --allow-downgrades

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'


      - name: package backend with Maven
        run: |
          cd backend
          mvn package
          mvn spring-boot:run

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'
          distribution: 'node'

      - name: run front
        run: |
          cd staff_portal
          npm install
          npm start

      - name: Run functional tests
        run: |
          cd backend
          mvn test -Dtest=*TestRunner
            
        

          
        
          


